export const guestLinkInfoRequests = {
  LINK_INFO_REQUEST: "LINK_INFO_REQUEST",
  LINK_INFO_SUCCESS: "LINK_INFO_SUCCESS",
  LINK_INFO_ERROR: "LINK_INFO_ERROR",
};

export const guestLinksByTagNameRequests = {
  LINKS_BY_TAG_NAME_REQUEST: "LINKS_BY_TAG_NAME_REQUEST",
  LINKS_BY_TAG_NAME_SUCCESS: "LINKS_BY_TAG_NAME_SUCCESS",
  LINKS_BY_TAG_NAME_ERROR: "LINKS_BY_TAG_NAME_ERROR",
};

export const userLinksActions = {
  ADD_LINK: "ADD_LINK",
  EDIT_LINK: "EDIT_LINK",
  REMOVE_LINK: "REMOVE_LINK",
};

export const signInRequests = {
  SIGN_IN_REQUEST: "SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_ERROR: "SIGN_IN_ERROR",
};

export const signOutRequests = {
  SIGN_OUT_REQUEST: "SIGN_OUT_REQUEST",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_ERROR: "SIGN_OUT_ERROR",
};

export const signUpRequests = {
  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
};
